### ISSUE TITLE
What is goal of development?

### ISSUE THREAD

**Issue by PASAf** [inolen/dreavm#14]
I mean, there are few open-source emulators already exists: lxdream, reicast, nulldc...
Why you've decided to start develop a new one?
What goals you are trying to reach? What you will solve with your version? What direction of development?

Thanks.

**Comment by inolen** [comment]
My only goal is education.

**Comment by vgturtle127** [comment]
@PASAf @inolen Well, also the Dreamcast emulation has been really lacking. It would be nice to see DreaVM become a full emulator/debugger with full development tools and such. This seems like the appropriate direction to go if you want a better emulator anyway. I like the trace viewer, and I would like to see a wireframe mode and maybe a disassembler/debugger implemented?

**Comment by inolen** [comment]
No problem. Debugger is coming, I did a lot of prep work a few weeks back. I think I'm going to do a push to stub out audio and get more games working soon, at which point I'll probably wrap up the debugger work.

**Comment by vgturtle127** [comment]
@inolen Awesome, dude! This is going to be such a cool project!

So do you know of any development/debugger features that other emulators have that you haven't implemented? I can't think of non-gaming features in DEmul, nullDC, Reicast, etc.

**Comment by PASAf** [comment]
I agree with @vgturtle127 that advanced debugger will be outstanding feature. It present in private DEmul version, but it is not available for public and closed-source. So if you provide developers with rich debugging features (and if your emulator will strive to match real hardware) this will be really unique project.

**Comment by vgturtle127** [comment]
@PASAf And the first to have such development and debugging tools in a Dreamcast emulator, if I am not mistaken.

This won't just make Dreamcast homebrew and stuff easier, but also make the emulator easier to contribute to!

I'm just so excited for this! :laughing:

**Comment by inolen** [comment]
@vgturtle127 nulldc and reicast have had debuggers in the past, it's just a frustrating thing to maintain at times.

I doubt I'll work on a GUI, I'd rather invest that time in learning about libretro and perhaps integrating with that.

On that line, the debugger will just be a gdb server implementation. That will let you connect with gdb and step through the guest code. I also believe Visual Studio can now act as a frontend for a gdb server if a graphical UI is more your style.

**Comment by vgturtle127** [comment]
@inolen Oh, OK.

Man, everybody really likes libretro. :smile:  I mean, so do I, don't get me wrong, but I prefer setting everything up manually for some reason. :stuck_out_tongue_closed_eyes: 

A GDB sounds good, mGBA uses that I think and that is a pretty good implementation as far as I have heard. I know XQEMU (and regular QEMU, for that matter) support a GDB server as well.

I will have to check out the Visual Studio GDB stuff, thanks for the info.

**Comment by PASAf** [comment]
Debugger in nullDC is almost useless, since its emulation is far from what real hardware do.
DEmul is closest one, not ideal, but we, mere mortals, have no access to latest version (only leaked 0.4.9).
I don't know much about reicast debugger, though.

**Comment by vgturtle127** [comment]
@PASAf Yeah, I doubt it was amaze-balls. :laughing: 

DEmul has many issues, most of them stemming around the lack of source and lack of documentation.
