### ISSUE TITLE
improve texture invalidation

### ISSUE THREAD

**Issue by inolen** [inolen/dreavm#5]
Currently, on _every_ write to texture memory we try to invalidate a texture cached for that address.

In addition to being completely wrong (partial write won't invalidate) it's incredibly slow - it was a quick hack to get the main menu working.

Need to add some kind of protect()-esque support to the Memory class so we can get a callback on write to the texture.

**Comment by inolen** [comment]
Closed with https://github.com/inolen/dreavm/commit/3248cc1acd859ad6e9838b54c293083980c99d28

**Comment by inolen** [comment]
Doh, just remembered I still need to support invalidating on palette changes:

https://github.com/inolen/dreavm/blob/master/src/hw/holly/tile_texture_cache.cc#L88

**Comment by inolen** [comment]
Closed again with 0d455e710a5d2f7dadaad1638d9098f938c7c442

Note, signal handlers for texture invalidation were removed for now.

I previously used signal handlers to catch writes to a texture's memory in order to invalidate. However, I did a test without signal handlers where I instead queried an interval tree (composed of texture start / end addresses) on _every_ write to video ram and learned it only took ~.02 ms of the frame for Crazy Taxi. With that in mind, I've removed the signal handlers to simplify things. @skmp warned me they may need to be added back once I start trying to emulate a game that plays movies - evidently they hit 300m+ writes per second to video ram.

**Comment by skmp** [comment]
I think I put a zero too much there (30M looks more plausible). Having a
full check for vram write makes the vram write path a ton slower though,
doesn't it? How do you handle it on the dynarec side? Sounds a lot more
complicated than a single mov

On Tue, Sep 22, 2015 at 2:29 AM, Anthony Pesch <notifications@github.com>
wrote:

> Closed #5 <https://github.com/inolen/dreavm/issues/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/inolen/dreavm/issues/5#event-415380461>.
>



-- 
~skmp
