### ISSUE TITLE
optimizing loads and stores

### ISSUE THREAD

**Issue by inolen** [inolen/dreavm#6]
Currently, every load / store goes through the memory page table system.

It'd be nice to:

* add new OP_LOAD_RAW / OP_STORE_RAW ops to operate on a constant address. `ConstantPropagationPass` should try and convert OP_LOAD / OP_STORE to this if possible.
* at runtime, patch OP_LOAD / OP_STORE operations to use a fixed address after they've been looked up the first time.

**Comment by inolen** [comment]
Some initial progress for the first bullet point was committed for the x64 backend:
https://github.com/inolen/dreavm/commit/bd678e4667bbe84bc2af9105e0137a004ff62eaa

Not sure there's much benefit in doing the same for the interpreter right now.

Investigating backpatching the emitted x64 code now.

**Comment by skmp** [comment]
A couple more interesting points for CP is, almost all constants are loaded from mem constant pools. If you have a memory load in the same page as the code is 99% a constant. Most pointers are also loaded that way. nullDC used to "constify" the first load so it had the address for the second one.

like

`
addr = readMem(pc +/- whatever); //const load
data = readMem(addr); //addr is 99.9% const here
`

**Comment by inolen** [comment]
Done with fe8b65797894ed5ca347d15c119585cfdb54688d
